"use client";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { useState, useEffect } from "react";
import { FaArrowUp } from "react-icons/fa";

export default function TermsOfUsePage() {
  const [showTopBtn, setShowTopBtn] = useState(false);

  // Scroll listener for Back to Top button
  useEffect(() => {
    const handleScroll = () => {
      if (window.scrollY > 300) {
        setShowTopBtn(true);
      } else {
        setShowTopBtn(false);
      }
    };
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  return (
    <main>
      <Header />

      {/* HERO */}
      <section className="w-full bg-[#f6fafd] py-16 flex justify-center">
        <div className="w-[90%] lg:w-[70%] text-center">
          <h1 className="text-4xl font-bold text-[#004188] mb-4">
            Terms and Conditions
          </h1>
          <p className="text-gray-600 text-lg">
            Please read these terms carefully before using our website.
          </p>
        </div>
      </section>

      {/* CONTENT */}
      <section className="w-full flex justify-center py-16">
        <div className="w-[90%] lg:w-[70%] text-gray-700 leading-relaxed space-y-12">
          {/* Agreement */}
          <div>
            <h2 className="text-2xl font-semibold text-[#004188] mb-4">
              Agreement between User and https://fastlinkleads.com
            </h2>

            <p>
              Welcome to https://fastlinkleads.com. The
              https://fastlinkleads.com website (the “Site”) is comprised of
              various web pages operated by Fast Link Leads (“FastLinkLeads”).
              https://fastlinkleads.com is offered to you conditioned on your
              acceptance without modification of the terms, conditions, and
              notices contained herein (the “Terms”). Your use of
              https://fastlinkleads.com constitutes your agreement to all such
              Terms. Please read these terms carefully and keep a copy of them
              for your reference.
            </p>

            <p className="mt-4">
              https://fastlinkleads.com is an E-Commerce Site.
            </p>

            <div className="mt-6 space-y-3">
              <p>
                <strong>Leads:</strong> We provide guaranteed promising leads in
                an area you specify, sold to you and you alone.
              </p>
              <p>
                <strong>Telemarketing:</strong> Our telemarketing staff will
                reach out on your behalf.
              </p>
              <p>
                <strong>SMS Marketing:</strong> Benefit from the instant
                attention generated by a text message. 95% of SMS messages are
                read in five minutes or less.
              </p>
              <p>
                <strong>Social Media:</strong> A social media profile managed
                professionally to generate attention and awareness.
              </p>
            </div>
          </div>

          {/* Privacy */}
          <div>
            <h2 className="text-2xl font-semibold text-[#004188] mb-4">
              Privacy
            </h2>
            <p>
              Your use of https://fastlinkleads.com is subject to
              FastLinkLeads’s Privacy Policy. Please review our Privacy Policy,
              which also governs the Site and informs users of our data
              collection practices.
            </p>
          </div>

          {/* Electronic Communications */}
          <div>
            <h2 className="text-2xl font-semibold text-[#004188] mb-4">
              Electronic Communications
            </h2>
            <p>
              Visiting https://fastlinkleads.com or sending emails to
              FastLinkLeads constitutes electronic communications. You consent
              to receive electronic communications and agree that all
              agreements, notices, disclosures and other communications that we
              provide electronically satisfy any legal requirement that such
              communications be in writing.
            </p>
          </div>

          {/* Children */}
          <div>
            <h2 className="text-2xl font-semibold text-[#004188] mb-4">
              Children Under Thirteen
            </h2>
            <p>
              FastLinkLeads does not knowingly collect personal information from
              persons under the age of thirteen. If you are under 18, you may
              use https://fastlinkleads.com only with permission of a parent or
              guardian.
            </p>
          </div>

          {/* Third Party Links */}
          <div>
            <h2 className="text-2xl font-semibold text-[#004188] mb-4">
              Links to Third Party Sites / Third Party Services
            </h2>

            <p>
              https://fastlinkleads.com may contain links to other websites
              (“Linked Sites”). The Linked Sites are not under the control of
              FastLinkLeads and FastLinkLeads is not responsible for the
              contents of any Linked Site, including without limitation any link
              contained in a Linked Site, or any changes or updates to a Linked
              Site. FastLinkLeads is providing these links to you only as a
              convenience, and the inclusion of any link does not imply
              endorsement by FastLinkLeads of the site or any association with
              its operators.
            </p>

            <p className="mt-4">
              Certain services made available via https://fastlinkleads.com are
              delivered by third party sites and organizations. By using any
              product, service or functionality originating from the
              https://fastlinkleads.com domain, you hereby acknowledge and
              consent that FastLinkLeads may share such information and data
              with any third party with whom FastLinkLeads has a contractual
              relationship to provide the requested product, service or
              functionality on behalf of https://fastlinkleads.com users and
              customers.
            </p>
          </div>

          {/* Intellectual Property */}
          <div>
            <h2 className="text-2xl font-semibold text-[#004188] mb-4">
              No Unlawful or Prohibited Use / Intellectual Property
            </h2>

            <p>
              You are granted a non-exclusive, non-transferable, revocable
              license to access and use https://fastlinkleads.com strictly in
              accordance with these terms of use. As a condition of your use of
              the Site, you warrant to FastLinkLeads that you will not use the
              Site for any purpose that is unlawful or prohibited by these
              Terms. You may not use the Site in any manner which could damage,
              disable, overburden, or impair the Site or interfere with any
              other party’s use and enjoyment of the Site. You may not obtain or
              attempt to obtain any materials or information through any means
              not intentionally made available or provided for through the Site.
            </p>

            <p className="mt-4">
              All content included as part of the Service, such as text,
              graphics, logos, images, as well as the compilation thereof, and
              any software used on the Site, is the property of FastLinkLeads or
              its suppliers and protected by copyright and other laws that
              protect intellectual property and proprietary rights. You agree to
              observe and abide by all copyright and other proprietary notices,
              legends or other restrictions contained in any such content and
              will not make any changes thereto.
            </p>

            <p className="mt-4">
              You will not modify, publish, transmit, reverse engineer,
              participate in the transfer or sale, create derivative works, or
              in any way exploit any of the content, in whole or in part, found
              on the Site. FastLinkLeads content is not for resale. Your use of
              the Site does not entitle you to make any unauthorized use of any
              protected content, and in particular you will not delete or alter
              any proprietary rights or attribution notices in any content. You
              will use protected content solely for your personal use, and will
              make no other use of the content without the express written
              permission of FastLinkLeads and the copyright owner. You agree
              that you do not acquire any ownership rights in any protected
              content. We do not grant you any licenses, express or implied, to
              the intellectual property of FastLinkLeads or our licensors except
              as expressly authorized by these Terms.
            </p>
          </div>

          {/* International Users */}
          <div>
            <h2 className="text-2xl font-semibold text-[#004188] mb-4">
              International Users
            </h2>

            <p>
              The Service is controlled, operated and administered by
              FastLinkLeads from our offices within the USA. If you access the
              Service from a location outside the USA, you are responsible for
              compliance with all local laws. You agree that you will not use
              the FastLinkLeads Content accessed through
              https://fastlinkleads.com in any country or in any manner
              prohibited by any applicable laws, restrictions or regulations.
            </p>
          </div>

          {/* Indemnification */}
          <div>
            <h2 className="text-2xl font-semibold text-[#004188] mb-4">
              Indemnification
            </h2>

            <p>
              You agree to indemnify, defend and hold harmless FastLinkLeads,
              its officers, directors, employees, agents and third parties, for
              any losses, costs, liabilities and expenses (including reasonable
              attorney’s fees) relating to or arising out of your use of or
              inability to use the Site or services, any user postings made by
              you, your violation of any terms of this Agreement or your
              violation of any rights of a third party, or your violation of any
              applicable laws, rules or regulations. FastLinkLeads reserves the
              right, at its own cost, to assume the exclusive defense and
              control of any matter otherwise subject to indemnification by you,
              in which event you will fully cooperate with FastLinkLeads in
              asserting any available defenses.
            </p>
          </div>

          {/* Arbitration */}
          <div>
            <h2 className="text-2xl font-semibold text-[#004188] mb-4">
              Arbitration
            </h2>

            <p>
              In the event the parties are not able to resolve any dispute
              between them arising out of or concerning these Terms and
              Conditions, or any provisions hereof, whether in contract, tort,
              or otherwise at law or in equity for damages or any other relief,
              then such dispute shall be resolved only by final and binding
              arbitration pursuant to the Federal Arbitration Act, conducted by
              a single neutral arbitrator and administered by the American
              Arbitration Association, or a similar arbitration service selected
              by the parties, in a location mutually agreed upon by the parties.
              The arbitrator’s award shall be final, and judgment may be entered
              upon it in any court having jurisdiction. In the event that any
              legal or equitable action, proceeding or arbitration arises out of
              or concerns these Terms and Conditions, the prevailing party shall
              be entitled to recover its costs and reasonable attorney’s fees.
              The parties agree to arbitrate all disputes and claims in regards
              to these Terms and Conditions or any disputes arising as a result
              of these Terms and Conditions, whether directly or indirectly,
              including Tort claims that are a result of these Terms and
              Conditions. The parties agree that the Federal Arbitration Act
              governs the interpretation and enforcement of this provision. The
              entire dispute, including the scope and enforceability of this
              arbitration provision shall be determined by the Arbitrator. This
              arbitration provision shall survive the termination of these Terms
              and Conditions.
            </p>
          </div>

          {/* Class Action Waiver */}
          <div>
            <h2 className="text-2xl font-semibold text-[#004188] mb-4">
              Class Action Waiver
            </h2>

            <p>
              Any arbitration under these Terms and Conditions will take place
              on an individual basis; class arbitrations and
              class/representative/collective actions are not permitted. THE
              PARTIES AGREE THAT A PARTY MAY BRING CLAIMS AGAINST THE OTHER ONLY
              IN EACH’S INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS
              MEMBER IN ANY PUTATIVE CLASS, COLLECTIVE AND/ OR REPRESENTATIVE
              PROCEEDING, SUCH AS IN THE FORM OF A PRIVATE ATTORNEY GENERAL
              ACTION AGAINST THE OTHER. Further, unless both you and
              FastLinkLeads agree otherwise, the arbitrator may not consolidate
              more than one person’s claims, and may not otherwise preside over
              any form of a representative or class proceeding.
            </p>
          </div>

          {/* Liability */}
          <div>
            <h2 className="text-2xl font-semibold text-[#004188] mb-4">
              Liability Disclaimer
            </h2>

            <p>
              THE INFORMATION, SOFTWARE, PRODUCTS, AND SERVICES INCLUDED IN OR
              AVAILABLE THROUGH THE SITE MAY INCLUDE INACCURACIES OR
              TYPOGRAPHICAL ERRORS. CHANGES ARE PERIODICALLY ADDED TO THE
              INFORMATION HEREIN. FAST LINK LEADS AND/OR ITS SUPPLIERS MAY MAKE
              IMPROVEMENTS AND/OR CHANGES IN THE SITE AT ANY TIME.
            </p>

            <p className="mt-4">
              FAST LINK LEADS AND/OR ITS SUPPLIERS MAKE NO REPRESENTATIONS ABOUT
              THE SUITABILITY, RELIABILITY, AVAILABILITY, TIMELINESS, AND
              ACCURACY OF THE INFORMATION, SOFTWARE, PRODUCTS, SERVICES AND
              RELATED GRAPHICS CONTAINED ON THE SITE FOR ANY PURPOSE. TO THE
              MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, ALL SUCH INFORMATION,
              SOFTWARE, PRODUCTS, SERVICES AND RELATED GRAPHICS ARE PROVIDED “AS
              IS” WITHOUT WARRANTY OR CONDITION OF ANY KIND. FAST LINK LEADS
              AND/OR ITS SUPPLIERS HEREBY DISCLAIM ALL WARRANTIES AND CONDITIONS
              WITH REGARD TO THIS INFORMATION, SOFTWARE, PRODUCTS, SERVICES AND
              RELATED GRAPHICS, INCLUDING ALL IMPLIED WARRANTIES OR CONDITIONS
              OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND
              NON-INFRINGEMENT.
            </p>

            <p className="mt-4">
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT
              SHALL FAST LINK LEADS AND/OR ITS SUPPLIERS BE LIABLE FOR ANY
              DIRECT, INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL
              DAMAGES OR ANY DAMAGES WHATSOEVER INCLUDING, WITHOUT LIMITATION,
              DAMAGES FOR LOSS OF USE, DATA OR PROFITS, ARISING OUT OF OR IN ANY
              WAY CONNECTED WITH THE USE OR PERFORMANCE OF THE SITE, WITH THE
              DELAY OR INABILITY TO USE THE SITE OR RELATED SERVICES, THE
              PROVISION OF OR FAILURE TO PROVIDE SERVICES, OR FOR ANY
              INFORMATION, SOFTWARE, PRODUCTS, SERVICES AND RELATED GRAPHICS
              OBTAINED THROUGH THE SITE, OR OTHERWISE ARISING OUT OF THE USE OF
              THE SITE, WHETHER BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT
              LIABILITY OR OTHERWISE, EVEN IF FAST LINK LEADS OR ANY OF ITS
              SUPPLIERS HAS BEEN ADVISED OF THE POSSIBILITY OF DAMAGES. BECAUSE
              SOME STATES/JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION
              OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, THE ABOVE
              LIMITATION MAY NOT APPLY TO YOU. IF YOU ARE DISSATISFIED WITH ANY
              PORTION OF THE SITE, OR WITH ANY OF THESE TERMS OF USE, YOUR SOLE
              AND EXCLUSIVE REMEDY IS TO DISCONTINUE USING THE SITE.
            </p>
          </div>

          {/* Termination */}
          <div>
            <h2 className="text-2xl font-semibold text-[#004188] mb-4">
              Termination / Access Restriction
            </h2>

            <p className="mt-4">
              FastLinkLeads reserves the right, in its sole discretion, to
              terminate your access to the Site and the related services or any
              portion thereof at any time, without notice. To the maximum extent
              permitted by law, this agreement is governed by the laws of the
              State of Delaware and you hereby consent to the exclusive
              jurisdiction and venue of courts in Delaware in all disputes
              arising out of or relating to the use of the Site. Use of the Site
              is unauthorized in any jurisdiction that does not give effect to
              all provisions of these Terms, including, without limitation, this
              section.
            </p>

            <p className="mt-4">
              You agree that no joint venture, partnership, employment, or
              agency relationship exists between you and FastLinkLeads as a
              result of this agreement or use of the Site. FastLinkLeads’s
              performance of this agreement is subject to existing laws and
              legal process, and nothing contained in this agreement is in
              derogation of FastLinkLeads’s right to comply with governmental,
              court and law enforcement requests or requirements relating to
              your use of the Site or information provided to or gathered by
              FastLinkLeads with respect to such use. If any part of this
              agreement is determined to be invalid or unenforceable pursuant to
              applicable law including, but not limited to, the warranty
              disclaimers and liability limitations set forth above, then the
              invalid or unenforceable provision will be deemed superseded by a
              valid, enforceable provision that most closely matches the intent
              of the original provision and the remainder of the agreement shall
              continue in effect.
            </p>

            <p className="mt-4">
              Unless otherwise specified herein, this agreement constitutes the
              entire agreement between the user and FastLinkLeads with respect
              to the Site and it supersedes all prior or contemporaneous
              communications and proposals, whether electronic, oral or written,
              between the user and FastLinkLeads with respect to the Site. A
              printed version of this agreement and of any notice given in
              electronic form shall be admissible in judicial or administrative
              proceedings based upon or relating to this agreement to the same
              extent and subject to the same conditions as other business
              documents and records originally generated and maintained in
              printed form. It is the express wish to the parties that this
              agreement and all related documents be written in English.
            </p>
          </div>

          {/* Changes */}
          <div>
            <h2 className="text-2xl font-semibold text-[#004188] mb-4">
              Changes to Terms
            </h2>

            <p>
              FastLinkLeads reserves the right, in its sole discretion, to
              change the Terms under which https://fastlinkleads.com is offered.
              The most current version of the Terms will supersede all previous
              versions. FastLinkLeads encourages you to periodically review the
              Terms to stay informed of our updates.
            </p>
          </div>

          {/* Contact */}
          <div className="bg-[#f6fafd] p-8 rounded-lg">
            <h2 className="text-2xl font-semibold text-[#004188] mb-4">
              Contact Us
            </h2>

            <div className="space-y-2">
              <p>
                FastLinkLeads welcomes your questions or comments regarding the
                Terms:
              </p>
              <p>Fast Link Leads</p>
              <p>200 Continental Dr</p>
              <p>Newark, Delaware 19713</p>
              <p>Email: support@fastlinkleads.com</p>
              <p>Phone: 844-884-5323</p>

              <p className="text-sm text-gray-500 mt-4">
                Effective as of January 01, 2023
              </p>
            </div>
          </div>
        </div>
      </section>

      <Footer />

      {/* BACK TO TOP BUTTON */}
      {showTopBtn && (
        <button
          onClick={scrollToTop}
          className="fixed bottom-8 right-4 lg:right-8 z-50 w-14 h-14 rounded-full bg-[#0858af] flex items-center justify-center text-white shadow-lg hover:scale-110 transition-transform duration-300"
        >
          <FaArrowUp size={20} />
        </button>
      )}
    </main>
  );
}
